apiVersion: v1
kind: ConfigMap
metadata:
  name: python-script
data:
  script.py: |
    import time

    def fib(n):
        if n <= 0:
            return 0
        elif n == 1:
            return 1
        else:
            a, b = 0, 1
            for _ in range(2, n+1):
                a, b = b, a + b
            return b

    def sum_fib(n):
        total = 0
        for i in range(1, n+1):
            total += fib(i)
        return total

    start = time.time()

    print("Start")
    n = 10000
    print("Sum of first", n, "Fibonacci numbers:", sum_fib(n))

    end = time.time()
    print("Time taken:", end - start, "seconds")

