apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: custom-application
commonLabels:
  app-name: echo-server
  app-version: v1

images:
  - name: alpine
    newName: "ubuntu"

resources:
- base/ns.yaml
- base/deployment.yaml
