apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: custom-application
commonLabels:
  app-name: echo-server
  app-version: v1

images:
  - name: kustomized/alpine
    newName: "alpine"

resources:
- base/ns.yaml
- base/deployment.yaml
- base/hello_world_pod.yaml
