apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: custom-application
commonLabels:
  app: echo-server
  app-version: v1
images:
  - name: ealen/echo-server
configMapGenerator:
  - name: cm-07
    behavior: create
    files:
      - files/config.json
      - files/script.py
    options:
      disableNameSuffixHash: true

resources:
- base/ns.yaml
- base/deployment.yaml

patches:
- target:
    kind: Deployment
    name: echo-deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: echo-deployment
      labels:
        patchLabel: patched
