apiVersion: v1
kind: Pod
metadata:
  name: mount-cm-pod
spec:
  containers:
    - name: hello-container
      image: alpine
      command: [ "/bin/sh" ]
      # NOTE: we are using echo so we see the output in logs
      args:
        - "-c"
        - |
          echo `cat "/etc/config/env.config_var"`
          sleep 3600
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-cm
