apiVersion: v1
kind: Namespace
metadata:
  name: ops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-namespaces
  namespace: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-namespaces
rules:
- apiGroups:
  - "*"
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-namespaces
subjects:
- kind: ServiceAccount
  name: monitor-namespaces
  namespace: ops
---
apiVersion: v1
data:
  add_docker_secret.sh: |
    #!/usr/bin/env bash

    ARRAY_COUNT=$(jq -r '. | length-1' "$BINDING_CONTEXT_PATH")
    BASE_NS='ops'
    # hooks are registered by calling --config. This should return hook's config.
    if [[ $1 == "--config" ]] ; then
      cat <<EOF
    configVersion: v1
    kubernetes:
    - name: "OnAddedKubeflowUser"
      apiVersion: v1
      kind: Namespace
      executeHookOnEvent: [ "Added" ]
    EOF
    else
      # ignore Synchronization for simplicity
      type=$(jq -r '.[0].type' "$BINDING_CONTEXT_PATH")

      if [[ $type == "Synchronization" ]] ; then
        echo Got Synchronization event
        exit 0
      fi
      echo "=================="
      echo $type
      echo $BINDING_CONTEXT_PATH
      echo "=================="

      for IND in $(seq 0 "${ARRAY_COUNT}")
      do
        bindingName=$(jq -r ".[$IND].binding" "$BINDING_CONTEXT_PATH")
        resourceName=$(jq -r ".[$IND].object.metadata.name" "$BINDING_CONTEXT_PATH")
        echo "Namespace $resourceName was created or modified."
        kubectl run echo --image=ealen/echo-server --restart=Never -n "$resourceName"
      done
    fi
kind: ConfigMap
metadata:
  name: secret-operator-hook
  namespace: ops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-operator
  namespace: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secret-operator
      name: secret-operator
    spec:
      containers:
      - image: flant/shell-operator:v1.2.0
        imagePullPolicy: Always
        name: shell-operator
        volumeMounts:
        - mountPath: /hooks
          name: hook
      serviceAccount: monitor-namespaces
      serviceAccountName: monitor-namespaces
      volumes:
      - configMap:
          defaultMode: 511
          name: secret-operator-hook
        name: hook
